### ISSUE TITLE
Gem: compile fails on OS X

### ISSUE THREAD

**Issue by itspriddle** [pressednet/fail24#7]
```
work/fail24/gem (master) % be rake compile
cd tmp/x86_64-darwin15.0/fail24_wrapper/2.1.7
make
compiling ../../../../ext/fail24_wrapper/fail24_wrapper.c
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
make: *** [fail24_wrapper.o] Error 1
rake aborted!
Command failed with status (2): [make...]
/Users/priddle/.gem/ruby/2.1.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:155:in `block (2 levels) in define_compile_tasks'
/Users/priddle/.gem/ruby/2.1.0/gems/rake-compiler-0.9.5/lib/rake/extensiontask.rb:154:in `block in define_compile_tasks'
Tasks: TOP => compile => compile:x86_64-darwin15.0 => compile:fail24_wrapper:x86_64-darwin15.0 => copy:fail24_wrapper:x86_64-darwin15.0:2.1.7 => tmp/x86_64-darwin15.0/fail24_wrapper/2.1.7/fail24_wrapper.bundle
(See full trace by running task with --trace)
```

Ruby: 2.1.7
OS X: 10.11 (15A282a)

**Comment by fabiokr** [comment]
@itspriddle Could you give master another try?

**Comment by jmazzi** [comment]
@fabiokr @itspriddle compiles for me on 10.11
